version: '2'
services:
  munin-node:
    restart: always
    image: plsit/munin-node
    build:
      context: .
    environment:
      ALLOW: "allow"
    volumes:
      - ./data/plugins:/var/lib/muninplugins
    privileged: true
    ports:
      - "4949:4949"